import type { Metadata } from "next";
import Logo from "@/app/icons/Logo";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid grid-cols-2">
      <section className="h-dvh bg-[#d9d9d9] flex justify-center items-center">
        <Logo />
      </section>
      <section className="h-dvh bg-[#f7f7f7] flex justify-center items-center">
        {children}
      </section>
    </div>
  );
}
